add_header Content-Security-Policy "default-src 'self'; base-uri 'none'; child-src 'none'; connect-src 'self'; font-src 'self'; form-action 'none'; frame-src 'none'; frame-ancestors 'none'; img-src 'self'; manifest-src 'self'; media-src 'self'; object-src 'none'; script-src 'self'; script-src-elem 'self'; script-src-attr 'none'; style-src 'self'; style-src-elem 'self'; style-src-attr 'none'; worker-src 'none'" always;
add_header X-Robots-Tag "noindex, noarchive, nofollow, noimageindex" always;
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
add_header Cache-Control "no-cache, no-store" always;
add_header X-Content-Type-Options "nosniff" always;
add_header X-Frame-Options "DENY" always;
add_header X-Permitted-Cross-Domain-Policies "none" always;
add_header Referrer-Policy "strict-origin-when-cross-origin" always;
add_header Permissions-Policy "camera=(), geolocation=(), microphone=(), payment=(), usb=(), serial=(), hid=()" always;
add_header X-Powered-By "Shrek" always;
